package com.tekcapzule.campaign.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.tekcapzule.core.domain.AggregateRoot;
import com.tekcapzule.core.domain.BaseDomainEntity;
import lombok.*;

@Data
@JsonIgnoreProperties(ignoreUnknown = true)
@EqualsAndHashCode(callSuper = true)
@DynamoDBTable(tableName = "Campaign")
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Lead extends BaseDomainEntity implements AggregateRoot {
    @DynamoDBHashKey(attributeName="campaignId")
    @DynamoDBAutoGeneratedKey
    private String leadId;
    @DynamoDBAttribute(attributeName = "firstName")
    private String firstName;
    @DynamoDBAttribute(attributeName = "lastName")
    private String lastName;
    @DynamoDBAttribute(attributeName = "emailId")
    private String emailId;
    @DynamoDBAttribute(attributeName = "company")
    private String company;
    @DynamoDBAttribute(attributeName = "jobTitle")
    private String jobTitle;
    @DynamoDBAttribute(attributeName = "phoneNumber")
    private String phoneNumber;
    @DynamoDBAttribute(attributeName = "country")
    private String country;
    @DynamoDBAttribute(attributeName = "comments")
    private String comments;
    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTypeConvertedEnum
    private Status status;
}
