package com.tekcapsule.campaign.domain.command;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.tekcapsule.campaign.domain.model.Highlight;
import com.tekcapsule.campaign.domain.model.Status;
import com.tekcapsule.core.domain.Command;
import lombok.Builder;
import lombok.Data;

import java.util.List;

@Data
@JsonIgnoreProperties(ignoreUnknown = true)
@Builder
public class CreateLeadCommand extends Command {
    private String firstName;
    private String lastName;
    private String emailId;
    private String company;
    private String jobTitle;
    private String phoneNumber;
    private String country;
    private String comments;
}

