package com.tekcapsule.campaign.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.tekcapsule.core.domain.AggregateRoot;
import com.tekcapsule.core.domain.BaseDomainEntity;
import lombok.*;


@Data
@JsonIgnoreProperties(ignoreUnknown = true)
@EqualsAndHashCode(callSuper = true)
@DynamoDBTable(tableName = "Campaign")
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Campaign extends BaseDomainEntity implements AggregateRoot {
    @DynamoDBHashKey(attributeName="campaignId")
    @DynamoDBAutoGeneratedKey
    private String campaignId;
    @DynamoDBAttribute(attributeName = "title")
    private String title;
    @DynamoDBAttribute(attributeName = "subTitle")
    private String subTitle;
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    @DynamoDBAttribute(attributeName = "startsOn")
    private String startsOn;
    @DynamoDBAttribute(attributeName = "endsOn")
    private String endsOn;
    @DynamoDBAttribute(attributeName = "offer")
    private String offer;
    @DynamoDBAttribute(attributeName = "resourceUrl")
    private String resourceUrl;
    @DynamoDBAttribute(attributeName = "imageUrl")
    private String imageUrl;
    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTypeConvertedEnum
    private Status status;
}

